//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace MyEshop2.Models
{
    internal class OrdersMetaData
    {
        public int OrderId { get; set; }
        public int UserId { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<bool> IsFinally { get; set; }

    }
}