//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace MyEshop2.Models
{
    internal class Product_GalleriesMetaData
    {
        public int GalleryID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string ImageName { get; set; }
    }
}