//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyEshop2.Models
{
    internal class Product_TagsMetaData
    {
        public int TagID { get; set; }
        public int ProductID { get; set; }
        public string TagTitle { get; set; }
    }
}