//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace MyEshop2.Models
{
    internal class ProductsMetaData
    {
        [Key]
        public int ProductID { get; set; }


        [Display(Name =" گروه محصول")]       
        [Required(ErrorMessage ="لطفا{0} را وارد کنید")]

        public int GroupID { get; set; }


        [Display(Name = "عنوان محصول ")]
        [Required(ErrorMessage = "لطفا{0} را وارد کنید")]


        public string ProductTitle { get; set; }

        [Display(Name = "توضیحات محصول ")]
        [Required(ErrorMessage = "لطفا{0} را وارد کنید")]
        [AllowHtml]
        [DataType(DataType.MultilineText)]
        public string ProductDescription { get; set; }

        [Display(Name = "مبلغ ")]
        [Required(ErrorMessage = "لطفا{0} را وارد کنید")]
        [DisplayFormat(DataFormatString = "{0:#,0}")]
        public int ProductPrice { get; set; }

        [Display(Name = "تصویر ")]
        [Required(ErrorMessage = "لطفا{0} را وارد کنید")]

        public string ProductImage { get; set; }

        [Display(Name = "تاریخ ثبت")]
        [DisplayFormat(DataFormatString ="{0:yyyy/MM/dd}")]
        public Nullable<System.DateTime> CreateDate { get; set; }

    }
}