//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace MyEshop2.Models
{
    internal class Product_GroupsMetaData
    {
        [Key]
        public int GroupID { get; set; }
        [Display(Name ="عنوان گروه ")]  
        [Required(ErrorMessage ="لطفا{0} را وارد کنید")]

        public string GroupTitle { get; set; }
    }
}