//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace MyEshop2.Models
{
    class UsersMetaData
    {
        [Key]
        public int UserID { get; set; }
        [Display(Name = "نقش کاربر")]
        [Required(ErrorMessage = "لطفا{0} را وارد کنید")]
        public int RoleID { get; set; }
        [Display(Name = "نام کاربری ")]
        [Required(ErrorMessage = "لطفا{0} را وارد کنید")]
        public string Username { get; set; }
        [Display(Name = "رمز عبور ")]
        [Required(ErrorMessage = "لطفا{0} را وارد کنید")]
        public string Password { get; set; }
        [Display(Name = "ایمیل ")]
        [Required(ErrorMessage = "لطفا{0} را وارد کنید")]
        public string Email { get; set; }
        [Display(Name = "کد فعال سازی ")]
        public string ActiveCode { get; set; }
        [Display(Name = "فعال/غیر فعال ")]
        public bool IsActive { get; set; }
        [Display(Name = "تاریخ ثبت نام ")]
        [DisplayFormat(DataFormatString = "{0:yyy/MM/dd}", ApplyFormatInEditMode = true)]

        public System.DateTime CreateDate { get; set; }


    }
}